name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Move Files
      run: |
        mkdir app
        mv !(dist) app/
        mv dist/* .

    - name: Deploy (Replace with your deployment steps)
      run: |
        # Add deployment steps here
        echo "Deployment steps go here"
