name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Commit and Push Build Artifacts
      run: |
        git config --local user.email "preciousdpb2000@gmail.com"
        git config --local user.name "Dumka-code"
        git add dist
        git commit -m "Add build artifacts"
        git push
