name: Create Directory and Push

on:
  push:
    branches:
      - main

jobs:
  create-directory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check if Directory Exists
      run: |
        if [ -d "makers" ]; then
          echo "Directory makers exists"
          # Add your update logic here, for example:
          # cp new-files/* /
        else
          echo "Directory makers does not exist, creating it"
          mkdir makers
          echo "Hello from makers" > makers/hello.txt
        fi

    - name: Move Root Content to makers
      run: |
        shopt -s extglob
        mkdir temp
        mv !(dist|.github) temp/

    - name: Move Temp Content to mkmks
      run: |
        mv temp/* makers/

    - name: Move Dist Contents to Root
      run: |
        mv dist/* .

    - name: Commit and Push
      run: |
        git config --local user.email "preciousdpb2000@gmail.com"
        git config --local user.name "Dumka-code"
        git add -A
        git commit -m "Update makers directory"
        git push https://${{ secrets.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 }}@github.com/Dumka-code/myportfolio.git HEAD:main
